// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models;

namespace Web.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20191129073337_inspeccion colgando de pajera")]
    partial class inspeccioncolgandodepajera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Models.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InspeccionId");

                    b.Property<string>("Name");

                    b.Property<int?>("PajeraId");

                    b.Property<int?>("SubPajeraId");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("PajeraId");

                    b.HasIndex("SubPajeraId");

                    b.ToTable("Adjunto");
                });

            modelBuilder.Entity("Web.Models.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PajeraId");

                    b.HasKey("Id");

                    b.HasIndex("PajeraId");

                    b.ToTable("Inspeccion");
                });

            modelBuilder.Entity("Web.Models.Pajera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pajera");
                });

            modelBuilder.Entity("Web.Models.SubPajera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PajeraId");

                    b.HasKey("Id");

                    b.HasIndex("PajeraId");

                    b.ToTable("SubPajera");
                });

            modelBuilder.Entity("Web.Models.Adjunto", b =>
                {
                    b.HasOne("Web.Models.Inspeccion", "Inspeccion")
                        .WithMany("Adjuntos")
                        .HasForeignKey("InspeccionId");

                    b.HasOne("Web.Models.Pajera", "Pajera")
                        .WithMany("Adjuntos")
                        .HasForeignKey("PajeraId");

                    b.HasOne("Web.Models.SubPajera", "SubPajera")
                        .WithMany("Adjuntos")
                        .HasForeignKey("SubPajeraId");
                });

            modelBuilder.Entity("Web.Models.Inspeccion", b =>
                {
                    b.HasOne("Web.Models.Pajera", "Pajera")
                        .WithMany("Inspecciones")
                        .HasForeignKey("PajeraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Models.SubPajera", b =>
                {
                    b.HasOne("Web.Models.Pajera", "Pajera")
                        .WithMany("SubPajeras")
                        .HasForeignKey("PajeraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
